# This file was auto-generated by salt's setup on Wednesday, 15 October 2014 @ 15:10:12 UTC.

from salt.version import SaltStackVersion

__saltstack_version__ = SaltStackVersion(2014, 1, 13, 0, 0, 0, None)
