# This file was auto-generated by salt's setup on Tuesday, 09 September 2014 @ 20:09:03 UTC.

from salt.version import SaltStackVersion

__saltstack_version__ = SaltStackVersion(2014, 1, 11, 0, 0, 0, None)
