# This file was auto-generated by salt's setup on Thursday, 12 February 2015 @ 18:02:23 UTC.

from salt.version import SaltStackVersion

__saltstack_version__ = SaltStackVersion(2014, 7, 2, 0, 0, 0, None)
